### ISSUE TITLE
500  Internal Server Error

### ISSUE THREAD

**Issue by MichaelKohler** [MichaelKohler/ese2012-web-ui#2]
After clicking a second time on "Buy Item" the following error is raised in the Error Console. The transaction still works. 
## 

[00:28:32.462] POST http://localhost:4567/buy_item [HTTP/1.1 500 Internal Server Error  12ms]

This might get fixed by issue #1.

**Comment by MichaelKohler** [comment]
"All exceptions raised within a request are now treated as internal server errors and result in a 500 response status."

from https://github.com/sinatra/sinatra/blob/master/CHANGES

**Comment by MichaelKohler** [comment]
## Stacktrace:

RuntimeError - Could not buy item!:
    ./app/controllers/../../app/models/market/user.rb:83:in `buy_item?'
    ./app/controllers/marketplace.rb:17:in`POST /buy_item'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:1264:in `call'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:1264:in`compile!'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:835:in `[]'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:835:in`route!'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:851:in `route_eval'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:835:in`route!'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:872:in `process_route'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:870:in`catch'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:870:in `process_route'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:834:in`route!'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:833:in `each'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:833:in`route!'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:936:in `dispatch!'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:769:in`call!'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:921:in `invoke'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:921:in`catch'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:921:in `invoke'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:769:in`call!'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:755:in `call'
    /var/lib/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb:22:in`call'
    /var/lib/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/path_traversal.rb:16:in `call'
    /var/lib/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/json_csrf.rb:17:in`call'
    /var/lib/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/base.rb:47:in `call'
    /var/lib/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb:22:in`call'
    /var/lib/gems/1.8/gems/rack-1.4.1/lib/rack/logger.rb:15:in `call'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:129:in`call'
    /var/lib/gems/1.8/gems/rack-1.4.1/lib/rack/head.rb:9:in `call'
    /var/lib/gems/1.8/gems/rack-1.4.1/lib/rack/methodoverride.rb:21:in`call'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/showexceptions.rb:21:in `call'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:99:in`call'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:816:in `forward'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:885:in`route_missing'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:846:in `route!'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:842:in`route!'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:936:in `dispatch!'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:769:in`call!'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:921:in `invoke'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:921:in`catch'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:921:in `invoke'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:769:in`call!'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:755:in `call'
    /var/lib/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb:22:in`call'
    /var/lib/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/path_traversal.rb:16:in `call'
    /var/lib/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/json_csrf.rb:17:in`call'
    /var/lib/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/base.rb:47:in `call'
    /var/lib/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb:22:in`call'
    /var/lib/gems/1.8/gems/rack-1.4.1/lib/rack/logger.rb:15:in `call'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:129:in`call'
    /var/lib/gems/1.8/gems/rack-1.4.1/lib/rack/head.rb:9:in `call'
    /var/lib/gems/1.8/gems/rack-1.4.1/lib/rack/methodoverride.rb:21:in`call'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/showexceptions.rb:21:in `call'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:99:in`call'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:816:in `forward'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:885:in`route_missing'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:846:in `route!'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:842:in`route!'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:936:in `dispatch!'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:769:in`call!'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:921:in `invoke'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:921:in`catch'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:921:in `invoke'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:769:in`call!'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:755:in `call'
    /var/lib/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb:22:in`call'
    /var/lib/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/path_traversal.rb:16:in `call'
    /var/lib/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/json_csrf.rb:17:in`call'
    /var/lib/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/base.rb:47:in `call'
    /var/lib/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb:22:in`call'
    /var/lib/gems/1.8/gems/rack-1.4.1/lib/rack/logger.rb:15:in `call'
    /var/lib/gems/1.8/gems/rack-1.4.1/lib/rack/commonlogger.rb:20:in`call_without_check'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:136:in `call'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:129:in`call'
    /var/lib/gems/1.8/gems/rack-1.4.1/lib/rack/head.rb:9:in `call'
    /var/lib/gems/1.8/gems/rack-1.4.1/lib/rack/methodoverride.rb:21:in`call'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/showexceptions.rb:21:in `call'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:99:in`call'
    /var/lib/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb:22:in `call'
    /var/lib/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/base.rb:47:in`call'
    /var/lib/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/path_traversal.rb:16:in `call'
    /var/lib/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/json_csrf.rb:17:in`call'
    /var/lib/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/base.rb:47:in `call'
    /var/lib/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb:22:in`call'
    /var/lib/gems/1.8/gems/rack-1.4.1/lib/rack/session/abstract/id.rb:205:in `context'
    /var/lib/gems/1.8/gems/rack-1.4.1/lib/rack/session/abstract/id.rb:200:in`call'
    /var/lib/gems/1.8/gems/rack-1.4.1/lib/rack/nulllogger.rb:9:in `call'
    /var/lib/gems/1.8/gems/rack-1.4.1/lib/rack/head.rb:9:in`call'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/showexceptions.rb:21:in `call'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:99:in`call'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:1389:in `call'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:1471:in`synchronize'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:1389:in `call'
    /var/lib/gems/1.8/gems/rack-1.4.1/lib/rack/handler/webrick.rb:59:in`service'
    /usr/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
    /usr/lib/ruby/1.8/webrick/httpserver.rb:65:in`run'
    /usr/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
    /usr/lib/ruby/1.8/webrick/server.rb:162:in`start'
    /usr/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
    /usr/lib/ruby/1.8/webrick/server.rb:95:in`start'
    /usr/lib/ruby/1.8/webrick/server.rb:92:in `each'
    /usr/lib/ruby/1.8/webrick/server.rb:92:in`start'
    /usr/lib/ruby/1.8/webrick/server.rb:23:in `start'
    /usr/lib/ruby/1.8/webrick/server.rb:82:in`start'
    /var/lib/gems/1.8/gems/rack-1.4.1/lib/rack/handler/webrick.rb:13:in `run'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:1350:in`run!'
    app/app.rb:37

**Comment by MichaelKohler** [comment]
The item can't be bought because it is inactive after the first click on "Buy Item".

=> We should reload the page (issue #1) => DUPLICATE
